import './globals.css'
import Header from '@/components/shared/Header'
import Footer from '@/components/shared/Footer'



export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='text-lg'>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
