import './globals.css'
import Header from '@/components/shared/Header'
import Footer from '@/components/shared/Footer'
import SupabaseProvider from './supabase-provider'


export const metadata = {
  title: 'NextQuiz: Test your friends\' Knowledge',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <body className='text-lg'>
        <SupabaseProvider session={session}>
          <Header />
          {children}
          <Footer />
        </SupabaseProvider>
      </body>
    </html>
  )
}
